### ISSUE TITLE
create_learner Opens Blank Text Input Box

### ISSUE THREAD

**Issue by DarioS** [mlr-org/mlr3extralearners#114]
When I ran `create_learner`, a text input box appeared.

![image](https://user-images.githubusercontent.com/631218/134093642-35dbcb7c-1830-4561-9628-d6fb515dd66a.png)

I typed in _hello world_ and clicked Save and in the resulting R template, there was no R6 class, but just the words _hello world_.

```
create_learner(pkg = "C:\\Program Files\\R\\R-4.1.0\\library\\mlr3extralearners",
               classname = "DLDA", algorithm = "Diagonal LDA for High-dimensional Data Sets",
               type = "classif", key = "DLDA", package = "sparsediscrim",
               caller = "dlda", feature_types = "numeric", predict_types = c("response", "prob"),
               properties = "twoclass", gh_name = "DarioS"
               )
```

It created a file named `learner_sparsediscrim_classif_DLDA.R` in `C:\Program Files\R\R-4.1.0\library\mlr3extralearners\R`.

Could you add to the documentation what to do if a pop-up text box appears?

**Comment by RaphaelS1** [comment]
Thanks, transferred to the correct repo. What IDE are you using? The function uses `file.edit` to open the newly created files, I can add an option to turn this off if `file.edit` isn't properly configured in your IDE but I can also post instructions for how to set this up properly.

**Comment by RaphaelS1** [comment]
Also just looking at your code I think it might be wrong. Generally this function should be called from within the pacdkage folder then the first argument should be `"."`. You seem to be directly adding the files into the installed package folder

**Comment by DarioS** [comment]
I use RStudio Desktop version 1.4. I know it's instructed to check out the package, but I was quickly trying it in the R library folder.

**Comment by RaphaelS1** [comment]
Usually `file.edit` will open the new files in new tabs but for whatever reason this isn't configured for you. So I propose adding an option at the end of the function to not open the files after a prompt. Thoughts on this? https://github.com/mlr-org/mlr3extralearners/pull/115

**Comment by RaphaelS1** [comment]
Closed in https://github.com/mlr-org/mlr3extralearners/pull/115/
