### ISSUE TITLE
[QTN] How do I add a learner to the dictionary?

### ISSUE THREAD

**Issue by rlwanggg** [mlr-org/mlr3extralearners#118]
### Expected Behaviour
I wanna add a new learner, and followed the steps carefully. But when I tested the learner by trying 

> lrn <- lrn(".key")

it showed an error.

### Actual Behaviour

Error: Element with key 'classif.abess' not found in DictionaryLearner!

### Reprex

Please use the `reprex` package to provide a minimal reproducible example of the bug. Please add the argument `si = TRUE` to include your session info.

**Comment by RaphaelS1** [comment]
I think you've answered this by opening #129 so I'm closing this issue
