### ISSUE TITLE
[LRNRQ] Add NNLS from package NNLS, along with other metalearner-focused learners

### ISSUE THREAD

**Issue by jmiahjones** [mlr-org/mlr3extralearners#128]
### Algorithm

Non-negative least-squares through the R package NNLS, Convex-Combination Least Squares through the R package quadprog, etc.

### Package

NNLS, quadprog, perhaps others

### Supported types

* [ ] classif
* [x] regr
* [ ] surv
* [ ] dens

### I have checked that this is not already implemented in

  * [x] mlr3
  * [x] mlr3learners
  * [x] mlr3extralearners
  * [ ] Other core packages (e.g. mlr3proba)

### Why do I think this is a useful learner?

For ensemble learning.

### Further Optional Comments

I'm intending this issue to spark a discussion. I've been using the legacy SuperLearner package in R to fit cross-validated and nested-cross-validated ensembles of learners. However, this package's ease of use also comes with a significant drawback in terms of extensibility. I recently came across the mlr3 project and have been test-driving it for some prediction tasks, and one of the biggest advantages I saw was the extensibility of this framework along with an appealing modularity.

So with all that said: I would like to start porting my ensemble learning pipelines slowly over to the mlr3 framework, but there are some gaps: the "metalearners" I typically used were things like NNLS for or CCLS for generating non-negative weights or a convex combination of base learners, respectively. Does it make sense to implement these learners here?

I'm sure I could be able to take a stab at this at some point, if you think it makes sense to put this in this package. Or should it go somewhere else?

**Comment by ck37** [comment]
This is listed as "completed" but is it truly, or is it incomplete? I also need the nnls learner for ensemble metalearning to migrate from SuperLearner.

**Comment by sebffischer** [comment]
I originally closed this because the OP did not respond anymore.

**Comment by sebffischer** [comment]
Currently I don't really have the time to implement this learner, so if you need this soon @ck37 it would be great if you could make a PR! :)

**Comment by ck37** [comment]
Thanks, yup I will make a PR

**Comment by jmiahjones** [comment]
Yes, sorry all. Student life got into crunch time and I forgot to update here.

I had sketched up a nnls learner, but I found that the pipeopregravg ensemble performed equally well. Those pipeopensemble learners use both, correct? If so, I believe this was a better approach anyway, since it could accommodate new metalearner models/losses more "automagically".
