### ISSUE TITLE
`mlr3extralearners::lrn` name conflict with `mlr3::lrn` 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3extralearners#133]
There is a name conflict between `mlr3extralearners::lrn` and `mlr3::lrn` 
@mllg @berndbischl I think this might be confusing to the user, as the functions behave differently depending on whether the required packages for the learner are installed (the mlr3extralearners function throws an error, while the mlr3 function does not). What do you think?

**Comment by mllg** [comment]
Agreed, can be removed. AFAIR you already get a warning from mlr3 if the required package is not installed.
