### ISSUE TITLE
Check that the create_learner function covers all possible features

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3extralearners#137]
When implementing new features (such as hotstarting) this has to be covered in the create_learner function. There should be a way to automatically check whether the create_learner function still covers all relevant properties)

**Comment by RaphaelS1** [comment]
Doesn't the template use mlr_reflections for this?

**Comment by sebffischer** [comment]
Yes (it was mostly a reminder for myself to check, maybe I shouldnt use issues for that)

**Comment by RaphaelS1** [comment]
Maybe just add "note to self" in issue name or something?
