### ISSUE TITLE
Possible bugs in various learners

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3extralearners#148]
`self$param_set$get_values()` is not used consistently. Every `.train()` method and every `.predict()` method should call them with the respective tags. This also includes predict methods for learners with no predict-time parameters because we encourage the user to extend the parameter set if we missed some parameters.

The Weka learners also call `get_values(tags = "pars")` which looks like a bug to me.

**Comment by sebffischer** [comment]
fully addressed in https://github.com/mlr-org/mlr3extralearners/commit/46daba8f1301fa2a3c959abe7ea35e77b5d0b67c
