### ISSUE TITLE
[BUGLRN] Bugs in learnerclassif.mob: Error in formals(fit) : argument "fit" is missing, with no default

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3extralearners#152]
### Expected Behaviour

slassif.mob learner works as expected.

### Actual Behaviour

Returns error:
```
Error in formals(fit) : argument "fit" is missing, with no default
```

### Reprex

```
task_ = tsk("german_credit")
task_$task_type
learner = lrn("classif.mob")
learner$predict_sets = c("train", "test")
learner$predict_type = "prob"
fm = learner$train(task_)
```

**Comment by sebffischer** [comment]
Thanks for reporting this. 
The documentation of the MOB learner should be better and will soon be improved (see the new [issue](https://github.com/mlr-org/mlr3extralearners/issues/154)). 

However you need to: 
1. Speficy the `fit` function as an argument, it specifies which models are fit in the leafs of the partition tree 
2. Specify the argument `rhs`, which specifies the z's as documented [here](https://rdrr.io/cran/party/man/mob.html) (i.e. the variables that control the paritioning) `rhs = ." would mean that all variables are used for partitioning. 
3. If you want probability predictions, you also need to specify the argument `predict_fun`

As a naive example, that only uses the variable "age" for partitioning. and uses a logit model with only an intercept: 

``` r
library(mlr3verse)
#> Loading required package: mlr3
task_ = tsk("german_credit")
logit_ = function(y, x, start = NULL, weights = NULL, offset = NULL, ...) {
  glm(y ~ 1, family = binomial, start = start, ...)
}

prob_vector_to_matrix = function(p, levs) {
  stopifnot(is.numeric(p))
  y = matrix(c(1 - p, p), ncol = 2L, nrow = length(p))
  colnames(y) = levs
  y
}
predict_fun = function(object, newdata, task, .type) {
  p = unname(predict(object, newdata = newdata, type = "response"))
  levs = task$levels(task$target_names)[[1L]]

  if (.type == "response") {
    ifelse(p < 0.5, levs[1L], levs[2L])
  } else {
    prob_vector_to_matrix(p, levs)
  }
}
learner = lrn("classif.mob", fit = logit_, predict_fun = predict_fun, rhs = "age")
learner$predict_sets = c("train", "test")
learner$predict_type = "prob"
fm = learner$train(task_)
```

<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you have any more questions feel free to ask.

**Comment by sebffischer** [comment]
@sumny please correct if I said anything incorrectly (don't want to spend a lot of time right now as I am on vacation) 
Also if you have time please please improve the docs
