### ISSUE TITLE
Update mlr3book chapter and functionality on how to add new learners

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3extralearners#174]

**Comment by a-humble-learner** [comment]
Dear @sebffischer, (assuming that you are a developer of mlr3?) I am hoping to use the [grpreg](https://cran.r-project.org/web/packages/grpreg/grpreg.pdf) package with mlr3. I believe grpreg has a lot in common with glmnet, where the latter has been incorporated into the mlr3 environment. Is there an easy way to do add grpreg? Is it straightforward for developers to add this as a new learner? If so, is there a time frame?
(I looked at the create_learner function but found the arguments rather confusing...) 
Thank you!

**Comment by sebffischer** [comment]
Hey, you can message me and we can arrange a zoom call, that might easiest :) sebf.fischer@gmail.com

**Comment by sebffischer** [comment]
This should also inform the user to use the "threads" parameter if applicable

**Comment by MosquitoFan** [comment]
I am also interested in the grpreg package, will the mlr3extralearners update this package in the future?

**Comment by sebffischer** [comment]
Sorry for the late response. I don't know when / if I will add it. The quickest way to get a new learner is to read the corresponding book section (https://mlr3book.mlr-org.com/extending.html#sec-extending-learners) and follow the procedure described. I will also review it and help you
