### ISSUE TITLE
install_learner only compatible with CRAN packages

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3extralearners#19]
Some learners, like `catboost` are not released on CRAN so `install_learner` doesn't work. These are rare cases but could consider more flexibility in the function

**Comment by RaphaelS1** [comment]
I would like to extend `install_learner` to be able to work with: 1. packages on CRAN, 2. packages on bioconductor, 3. packages on GitHub. My proposed method for doing so is:

1. Test if "\" present in package name
1. If yes then remotes from GitHub
1. If no then try `install.packages`
1. On fail try `BiocManager::install`

I think Bioconductor is low priority and can be implemented once we have learners from this. However GitHub would be a nice addition but for this proposed method to work would require allowing packages to be named accordingly, e.g. `mlr-org/mlr3`. This however would break `mlr3` functionality such as `lrn`. Would it be possible (@mllg) to extend these functions with an extra line:

```R
if(grepl("/", pkg)) pkg = strsplit(pkg, "/")[[1]][[2]]
```

Or alternative suggestions for GitHub installation also appreciated.

**Comment by berndbischl** [comment]
i think this should be good. and BC is really lower prior for now.

@mllg

**Comment by RaphaelS1** [comment]
https://github.com/mlr-org/mlr3/issues/617
