### ISSUE TITLE
how can I save the lgbm model?

### ISSUE THREAD

**Issue by Raymond-KT** [mlr-org/mlr3extralearners#206]
hello, I appreciate for your help. 

I want to save my lgbm model. 
But I can't. 

I used save function like below, 

```r
learner <-  mlr3::lrn("classif.lightgbm")

learner$train(task_train)

lightgbm::lgb.save(
  booster = learner$model,
  filename = paste0("lgbmodel_0519" , ".txt"),
  num_iteration = learner$model$current_iter()
)

saveRDS.lgb.Booster(learner$model, "lgbmodel.rds")

```

But when I load a model from that file, I can't use that model. 

I got error message like below.
```

> saveRDS.lgb.Booster(learner$model, "lgbmodel.rds")
> model_test <- readRDS.lgb.Booster("lgbmodel.rds")
> model_test$predict(test_2022)
Error in numeric(npred) : vector size cannot be NA 


```

here is my model info:

```r

> learner
<LearnerClassifLightGBM:classif.lightgbm>
* Model: lgb.Booster
* Parameters: verbose=-1, nrounds_by_cv=TRUE, nfolds=5, objective=binary
* Packages: mlr3, lightgbm
* Predict Type: prob
* Feature types: numeric, integer
* Properties: importance, missings, multiclass, twoclass, weights


> learner$model
<lgb.Booster>
  Public:
    add_valid: function (data, name) 
    best_iter: -1
    best_score: NA
    current_iter: function () 
    dump_model: function (num_iteration = NULL, feature_importance_type = 0L) 
    eval: function (data, name, feval = NULL) 
    eval_train: function (feval = NULL) 
    eval_valid: function (feval = NULL) 
    finalize: function () 
    initialize: function (params = list(), train_set = NULL, modelfile = NULL, 
    lower_bound: function () 
    params: list
    predict: function (data, start_iteration = NULL, num_iteration = NULL, 
    raw: tree
    version=v3
    num_class=1
    num_tree_per_iteration=1
    lab ...
    record_evals: list
    reset_parameter: function (params, ...) 
    rollback_one_iter: function () 
    save: function () 
    save_model: function (filename, num_iteration = NULL, feature_importance_type = 0L) 
    save_model_to_string: function (num_iteration = NULL, feature_importance_type = 0L) 
    set_train_data_name: function (name) 
    to_predictor: function () 
    update: function (train_set = NULL, fobj = NULL) 
    upper_bound: function () 
  Private:
    eval_names: NULL
    get_eval_info: function () 
    handle: lgb.Booster.handle
    higher_better_inner_eval: NULL
    init_predictor: NULL
    inner_eval: function (data_name, data_idx, feval = NULL) 
    inner_predict: function (idx) 
    is_predicted_cur_iter: list
    name_train_set: training
    name_valid_sets: list
    num_class: 1
    num_dataset: 1
    predict_buffer: list
    set_objective_to_none: FALSE
    train_set: lgb.Dataset, R6
    train_set_version: 1
    valid_sets: list
```

**Comment by sebffischer** [comment]
So the problem is that the `lightgbm` learner cannot be saved with the usual `saveRDS` I believe, so you need to save the learner's state (without the model) using saveRDS and the model using the lightgbm save function and then merge them together afterwards. The following seems to be working: 

``` r
library(mlr3extralearners)
library(mlr3)

learner = lrn("classif.lightgbm")
task_train = tsk("iris")

learner$train(task_train)
state = learner$state
model = learner$model
state$model = NULL

saveRDS(state, "state.rds")
lightgbm::lgb.save(
  booster = model,
  filename = "model.rds",
  num_iteration = learner$model$current_iter()
)

state_loaded = readRDS("state.rds")
model_loaded = lightgbm::lgb.load("model.rds")
state_loaded$model = model_loaded

learner = lrn("classif.lightgbm")

learner$state = state_loaded

learner$predict(task_train)
#> <PredictionClassif> for 150 observations:
#>     row_ids     truth  response  prob.setosa prob.versicolor prob.virginica
#>           1    setosa    setosa 9.999852e-01    1.382390e-05   9.720637e-07
#>           2    setosa    setosa 9.999263e-01    6.613751e-05   7.548791e-06
#>           3    setosa    setosa 9.999859e-01    1.261789e-05   1.494298e-06
#> ---                                                                        
#>         148 virginica virginica 2.707061e-06    3.682518e-05   9.999605e-01
#>         149 virginica virginica 2.201095e-05    1.046058e-04   9.998734e-01
#>         150 virginica virginica 4.883481e-05    4.620961e-03   9.953302e-01
```

<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Raymond-KT** [comment]
I'm really really thank you for your reply!!!

I can save the state.rds,  but I can't save the model.rds. 
I got an error message like below. 

```{r}
lightgbm::lgb.save(
  booster = model,
  filename = "model.rds",
  num_iteration = learner$model$current_iter()
)

Error in lightgbm::lgb.save(booster = model, filename = "model.rds", 
num_iteration = learner$model$current_iter()) :  lgb.save: booster should be an ‘lgb.Booster’

```

Is there any solution to save my model T-T?

**Comment by Raymond-KT** [comment]
And I runned your code,  but i faced to this error. 

thankyou for your help!!!

```r
learner$predict(task_train)
Error in data.table::setcolorder(newdata, private$dtrain$get_colnames()) : 
  attempt to apply non-function

```









> So the problem is that the `lightgbm` learner cannot be saved with the usual `saveRDS` I believe, so you need to save the learner's state (without the model) using saveRDS and the model using the lightgbm save function and then merge them together afterwards. The following seems to be working:
> 
> ```r
> library(mlr3extralearners)
> library(mlr3)
> 
> learner = lrn("classif.lightgbm")
> task_train = tsk("iris")
> 
> learner$train(task_train)
> state = learner$state
> model = learner$model
> state$model = NULL
> 
> saveRDS(state, "state.rds")
> lightgbm::lgb.save(
>   booster = model,
>   filename = "model.rds",
>   num_iteration = learner$model$current_iter()
> )
> 
> state_loaded = readRDS("state.rds")
> model_loaded = lightgbm::lgb.load("model.rds")
> state_loaded$model = model_loaded
> 
> learner = lrn("classif.lightgbm")
> 
> learner$state = state_loaded
> 
> learner$predict(task_train)
> #> <PredictionClassif> for 150 observations:
> #>     row_ids     truth  response  prob.setosa prob.versicolor prob.virginica
> #>           1    setosa    setosa 9.999852e-01    1.382390e-05   9.720637e-07
> #>           2    setosa    setosa 9.999263e-01    6.613751e-05   7.548791e-06
> #>           3    setosa    setosa 9.999859e-01    1.261789e-05   1.494298e-06
> #> ---                                                                        
> #>         148 virginica virginica 2.707061e-06    3.682518e-05   9.999605e-01
> #>         149 virginica virginica 2.201095e-05    1.046058e-04   9.998734e-01
> #>         150 virginica virginica 4.883481e-05    4.620961e-03   9.953302e-01
> ```
> 
> Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

**Comment by sebffischer** [comment]
> 

please provide a complete reprex

**Comment by sebffischer** [comment]
so you are not saving a model but an AutoTuner?

**Comment by Raymond-KT** [comment]
I really appreciate your kindness.

first, I runned your code on my rstudio but I got an error message. 

```r
library(mlr3extralearners)
library(mlr3)

learner = lrn("classif.lightgbm")
task_train = tsk("iris")

learner$train(task_train)
state = learner$state
model = learner$model
state$model = NULL

saveRDS(state, "state.rds")
lightgbm::lgb.save(
  booster = model,
  filename = "model.rds",
  num_iteration = learner$model$current_iter()
)

state_loaded = readRDS("state.rds")
model_loaded = lightgbm::lgb.load("model.rds")
state_loaded$model = model_loaded

learner = lrn("classif.lightgbm")

learner$state = state_loaded

learner$predict(task_train)

#>Error in data.table::setcolorder(newdata, private$dtrain$get_colnames()) : 
#>  attempt to apply non-function

```

**Comment by Raymond-KT** [comment]
And, this is my code. 
but I have a problem to save my model.


```r
library(mlr3verse)

# train/test split
train_set <- sample(nrow(demo_modeling), 0.8 * nrow(demo_modeling))
test_set <- setdiff(seq_len(nrow(demo_modeling)), train_set)

train_set %>% length()
test_set %>% length()

task <- as_task_classif(demo_modeling, target = 'turnover', positive = '1')

task_train <- demo_modeling[train_set,]
task_train %>% nrow()
task_train <- as_task_classif(task_train, target = 'turnover', positive = '1')

task_test <- demo_modeling[test_set,]
task_test %>% nrow()
task_test <- as_task_classif(task_test, target = 'turnover', positive = '1')

# train the model
learner$train(task_train)

# parameter setting
search_space = ps(
  learning_rate= p_dbl(lower = 0.01, upper = 0.05), 
  num_leaves= p_int(lower= 31 ,upper = 60),
  max_depth = p_int(lower=1, upper = 20)
)

terminator = trm("evals", n_evals = 10)
tuner = tnr("random_search")

# AutoTuner
at = AutoTuner$new(
  learner = learner,
  resampling = rsmp("holdout"),
  measure = msr("classif.ce"),
  search_space = search_space,
  terminator = terminator,
  tuner = tuner
)

# training 
at$train(task_train)

# check the result
at$tuning_result
# learning_rate num_leaves max_depth learner_param_vals  x_domain classif.ce
# 1:    0.04270429         43        10          <list[7]> <list[3]> 0.02570379

as.data.table(at$archive)

# save the model

state = at$state
model = at$model
state$model = NULL

saveRDS(state, "state.rds")

lightgbm::lgb.save(
  booster = model,
  filename = "model.rds",
  num_iteration = at$model$current_iter()
)

# Error in lightgbm::lgb.save(booster = model, filename = "model.rds", num_iteration = at$model$current_iter()) : 
#   lgb.save: booster should be an ‘lgb.Booster’


```

**Comment by sebffischer** [comment]
Which mlr3 / mlr3extralearners are you using, can you update to the latest versions?

**Comment by Raymond-KT** [comment]
Yes! I updated to the latest version.
Is it an unique situation? then, I'll try to use another computer!

![image](https://user-images.githubusercontent.com/51352487/169350164-04b35e29-2d78-4e0b-a66d-5b1e8663b3d9.png)



> Which mlr3 / mlr3extralearners are you using, can you update to the latest versions?

**Comment by sebffischer** [comment]
From that it looks like you don't have `mlr3extralearners`  installed but you use the old package `mlr3learners.lightgbm`

**Comment by sebffischer** [comment]
Please provide a reprex of your probem https://github.com/tidyverse/reprex
(A minimal exaple that actually runs, i.e. exactly describes your problem). 

And use `mlr3extralearners` for that, you can install by running

`remotes::install_github("mlr-org/mlr3extralearners")`

and in case you don't have the "remotes" package run the following: 

`install.packages("remotes")`

**Comment by Raymond-KT** [comment]
@sebffischer 

As you mentioned above, it works well after updating all the packages!!
Thank you so much!!!!!
