### ISSUE TITLE
[BKLRN] Learner regr.M5Rules broken sanity test(s)

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3extralearners#23]
Link to broken build and/or error message:

https://github.com/mlr-org/mlr3extralearners/runs/1163993777?check_suite_focus=true#step:8:344

Sanity test has been excluded for now.

**Comment by sebffischer** [comment]
fixed in https://github.com/mlr-org/mlr3extralearners/commit/43c348b3adfd7526d81f3e5923668e8982267ebc
