### ISSUE TITLE
Add glmer from lme4

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3extralearners#243]
See discussion here: https://github.com/mlr-org/mlr3extralearners/issues/197

**Comment by T-Reiter** [comment]
Hey there, 
I just came to read about this thread and issue and am super interested in using the glmer learner in mlr3. As described by @FlorianPargent in the original thread I am just working on a project in which I am having a classification task with experience sampling/intensive longitudinal data. So far I am using the cv.glmnet and ranger learners with blocked resampling but it would be super cool to have mixed effects classification implemented in mlr3. What do you think, when this learner might be available? As the lme regression is already implemented, I dare to hope that this could be implemented rather easily?
Best and looking forward to testing it! Keep on with the great work on mlr3!

**Comment by T-Reiter** [comment]
Great, thanks for your quick reply!
