### ISSUE TITLE
[LRNRQ] Add <mlfitppml> from package <penppml>

### ISSUE THREAD

**Issue by shihu90** [mlr-org/mlr3extralearners#248]
### Algorithm

<mlfitppml>

### Package

<penppml>

### Supported types

* [ ] classif
* [ ] clust 
* [ ] dens
* [x] regr
* [ ] surv

### I have checked that this is not already implemented in

  * [ ] mlr3
  * [ ] mlr3learners
  * [ ] mlr3extralearners
  * [ ] Other core packages (e.g. mlr3proba, mlr3keras)

### Why do I think this is a useful learner?
It is useful for gravity equation in international economics. 
### Further Optional Comments

(e.g. if this algorithm is already implemented under a different learner then please explain why this additional implementation is useful)

**Comment by sebffischer** [comment]
Hey and thanks for your interest in mlr3! Are you interested in implementing that yourself? 

Otherwise we will not implement this, as the package has only around 300 monthly downloads. 
If you are willing to do it yourself, I am happy to help you. :)

**Comment by shihu90** [comment]
Dear Sebastian,

Thank you for your positive reply. It would be nice that you could provide some help on implementing this package in mlr3.

Thank you again and best regards,
Shiyun Hu


[JGU] <https://www.uni-mainz.de/>



Shiyun Hu, M.Sc.,

Chair of International Economic Policy<http://www.public.economics.uni-mainz.de/>

***@***.******@***.***> • +49 (0) 1520-5381814

Johannes Gutenberg-Universität Mainz, Johann-Joachim-Becher-Weg 31, 55099 Mainz<https://goo.gl/maps/SzGuP8tZgCtrhk1Y7>

**Comment by sebffischer** [comment]
You should start out by reading and following the tutorial given here: https://mlr3book.mlr-org.com/extending.html#sec-extending-learners If you are stuck, let me know!

**Comment by sebffischer** [comment]
This learner has no predict method, hence I am closing this issue!
