### ISSUE TITLE
Add mlr3torch

### ISSUE THREAD

**Issue by grantmcdermott** [mlr-org/mlr3extralearners#28]
### Algorithm

Example

```r
library(torch)

model <- nn_module(
 initialize = function() {
   self$conv1 <- nn_conv2d(1, 20, 5)
   self$conv2 <- nn_conv2d(20, 20, 5)
 },
 forward = function(input) {
   input <- self$conv1(input)
   input <- nnf_relu(input)
   input <- self$conv2(input)
   input <- nnf_relu(input)
   input
 }
)
```

### Package

torch

### Supported types

* [x] classif
* [x] regr
* [ ] surv
* [ ] dens

### I have checked that this is not already implemented in

  * [x] mlr3
  * [x] mlr3learners
  * [x] mlr3extralearners
  * [x] Other core packages (e.g. mlr3proba)

### Comments

The new torch package brings native R bindings to the underlying Torch libraries (no need for Python intermediaries). A potential point of convenience is that everything (AFAICT) is already defined in terms of R6 classes. There's obviously a lot more functionality to Torch beyond `nn_module`, but it strikes me as the most important algorithm for mlr3 users.

- Introductory blog post: https://blogs.rstudio.com/ai/posts/2020-09-29-introducing-torch-for-r/
- pkgdown site: https://torch.mlverse.org/docs/index.html

**Comment by RaphaelS1** [comment]
Ah of course this comes out just after I get a package on cran using reticulate for this...

That aside have you tried out mlr3keras? A torch learner isn't really a single model so would probably need a more sophisticated interface like in mlr3keras.

**Comment by RaphaelS1** [comment]
We've discussed internally and decided that this is a good idea but that majority of people will be happy with mlr3keras. We will implement mlr3torch once someone has the time to do this, feel free if you're able !

**Comment by grantmcdermott** [comment]
Thanks @RaphaelS1.

Realistically, I don't have time rn to commit to this either; I mostly wanted to put it on your radar.  On that note: sorry to be the bearer of bad (good?) news about the non-Python implementation.

I actually haven't given mlr3keras a go, though I'm well acquainted with with the native library. Will check it out ;-)

Feel free to close if you'd like.

**Comment by RaphaelS1** [comment]
> Feel free to close if you'd like.

I'll keep it open as a way to find contributors and to see how many people are interested in the idea.

**Comment by loveyu3317** [comment]
Torch is a good framework for deep learning in scientific research. I would like to see it in mlr3 family.

**Comment by statist-bhfz** [comment]
> 
> 
> Torch is a good framework for deep learning in scientific research. I would like to see it in mlr3 family.

Totally agree with you. Also anticipating for `torch` learner in `mlr3`.

**Comment by RaphaelS1** [comment]
This is now being implemented here https://github.com/mlr-org/mlr3torch
