### ISSUE TITLE
randomForestSRC's parameter perf.type cannot be set

### ISSUE THREAD

**Issue by stepangordeev** [mlr-org/mlr3extralearners#280]
### Description

functions `rfsrc`, `imbalanced`, etc. in randomForestSRC have an optional argument `perf.type`. However, learners for this package do not recognize it as a parameter.

### Reproducible example

``` r
library(mlr3)
library(mlr3extralearners)
library(randomForestSRC)
#> 
#>  randomForestSRC 3.2.1 
#>  
#>  Type rfsrc.news() to see new features, changes, and bug fixes. 
#> 
task = tsk("breast_cancer")
learner <- lrn(
    "classif.rfsrc",
    perf.type = "gmean"
)
#> Error: Cannot set argument 'perf.type' for 'LearnerClassifRandomForestSRC' (not a constructor argument, not a parameter, not a field.
```

<sup>Created on 2023-06-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
Hey and thank you for reporting this!
I have not implemented the learner myself, but it states that this parameter was not implemented because scoring in `mlr3` is done with `Measure`s. I am not familiar with the learner. Can you tell me why you wanted to use this parameter / why this is not possible using measures?

**Comment by stepangordeev** [comment]
That makes sense, but the issue is that `rfsrc` uses `perf.type` as a metric for constructing variable importance (even if you call `vimp()` after the fact, it just reads the parameter that was set for the forest). For my application, I have to use the package's own variable importance measure, so I need a way to control it.

**Comment by sebffischer** [comment]
Thanks for the clarification. Just to be sure: You only need these parameters during `$train()`, right?

**Comment by sebffischer** [comment]
Can you please install `devtools::install_github("mlr-org/mlr3extralearners@rfsrc")` and tell me whether this solves your problem?

**Comment by stepangordeev** [comment]
Yes, it works now! Thank you
