### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3extralearners#32]
- When running `pkgdown::build_site()` locally I set

```r
Warning messages:
1: In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'akritas' 
2: In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'predict.akritas' 
3: Topics missing from index: 
* lrn 
4: Failed to parse example for topic 'create_learner' 
```

- I've optimized the "search learner" table with respect to font-size and padding upstream in mlr3pkgdowntemplate

- I think both overview tables should have a top level entry in the menu bar in the pkgdown site. Currently they are hidden in the "learners" dropdown. If horizontal space becomes an issue, I suggest to first remove the stackoverflow and mattermost badges.

**Comment by RaphaelS1** [comment]
> When running pkgdown::build_site() locally I set

Fixed the problems there

> I've optimized the "search learner" table with respect to font-size and padding upstream in mlr3pkgdowntemplate

Thanks looks much better!

> I think both overview tables should have a top level entry in the menu bar in the pkgdown site. Currently they are hidden in the "learners" dropdown. If horizontal space becomes an issue, I suggest to first remove the stackoverflow and mattermost badges.

Okay! I considered merging them into one table by just adding the learner status, but separating them still seems sensible as both are important separately.

**Comment by pat-s** [comment]
Styling and presentation is always subjective. Maybe merging is even a good idea. But it might hide the second table way down below the first one which might not be so good for users.

Also I spotted a missing package warning [here](https://mlr3extralearners.mlr-org.com/#installing-and-loading-learners).

**Comment by RaphaelS1** [comment]
> Also I spotted a missing package warning here.

No that's part of the example ;)

But yes I'll make it clearer that the point is that the package isn't installed there!

**Comment by pat-s** [comment]
Ah ok! Well I just flew over it and it caught my eye without reading it closely 😄
