### ISSUE TITLE
Remove hardcoded `VectorDistribution`s from survival learners

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3extralearners#327]
Two examples (there may be more):
- https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_partykit_surv_ctree.R
- https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_partykit_surv_cforest.R

**Comment by RaphaelS1** [comment]
@jemus42 this will fix the cforest bug you found

**Comment by bblodfon** [comment]
Note: the only other hard-coded `VectorDistribution`s are in `surv.parametric` (https://github.com/mlr-org/mlr3extralearners/issues/41) and `flexsurv` (https://github.com/mlr-org/mlr3extralearners/issues/318), both to be solved in other issues.

**Comment by jemus42** [comment]
Awesomesauce, thanks! 🙏🏻 

The thing is, I've realized one of our issues is the serialization of objects with environments, so the other two learners (`parametric` and `flexsurv`) also still affect my experiment as long as their prediction object includes a `$distr` slot that's not just a data.table 😬

**Comment by bblodfon** [comment]
`flexsurv` I will fix soon - for the `parametric`, we have to ask Raphael, cause it really returns `VectorDistributions` and not matrix-like object inside the `$data$distr` slot
