### ISSUE TITLE
update for `aorsf` version 0.1.2

### ISSUE THREAD

**Issue by bcjaeger** [mlr-org/mlr3extralearners#338]
Hello!

I am planning to release `aorsf` version 0.1.2 soon. This release will include support for classification and regression oblique random forests, and these new features introduce some new parameters into `orsf`, deprecate the current `orsf_control` functions in favor of outcome-specific ones, and replace the `orsf_fit` class with `ObliqueForest`. Last, the ArXiv paper that we reference in the mlr3 docs has now been published in Journal of Computational and Graphical Statistics, so the bib data can be updated. I've prepared a PR with these changes. Would it be okay for me to submit this PR for you to review?

**Comment by sebffischer** [comment]
Hey @bcjaeger, thanks a lot for actively maintaining the aorsf Learner! I am will be glad to review your Pull Request! :)

**Comment by bcjaeger** [comment]
Awesome! I will give it a review tonight and post it tomorrow. Thank you!
