### ISSUE TITLE
Unable to use "var.select" method of randomForestSRC 

### ISSUE THREAD

**Issue by littleisland8** [mlr-org/mlr3extralearners#374]
Hello. 

I would like to use Random forest minimal depth (method="md" of var.select method of randomForestSRC ) and random forest variable hunting (method="vh" of var.select method of randomForestSRC) approaches to perform feature selection on a survTask. 
I load the learner with: 
learner = lrn("surv.rfsrc", importance="permute")
When I try to run flt("importance", learner = learner) I am able to get the feature score based on permutation score as the learner got importance="permute" as parameter. However, I cannot use var.select method to perform minimal depth and variable hunting because in the mlr_filters dictionary I cannot find something related to var.select of randomForestSRC. 

How can I use var.select into the mlr3verse?

**Comment by bblodfon** [comment]
Hi @littleisland8,

As you've probably seen, for the `flt("importance", learner = learner)` to work, `learner$importance()` needs to return the importance scores of the features (usually from a default method from the package that implements the learner). `randomForestSRC::var.select` seems more like a more elaborate/extra analysis variable selection method with a lot of parameters, and maybe more suited to variable selection.

If you really want to and can get some sort of importance scores such a function, then I would suggest extending the erspective learner ([code line](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_randomForestSRC_surv_rfsrc.R#L62)) and override the `importance()` method by using inside `var.select`. Then using that new augmented learner with `mlr3filters::flt("importance", ...)` would work.
