### ISSUE TITLE
BART survival learner does not work on Windows 

### ISSUE THREAD

**Issue by drag05** [mlr-org/mlr3extralearners#393]
### Description

I have found so far two issues with the survival analysis example presented in Gallery:
1) Running the example on Windows :

```
learner = lrn("surv.bart", nskip = 250, ndpost = 50, keepevery = 10)
```

Although "surv.bart" learner uses function `surv.bart` from package `BART`:
```
> learner
<LearnerSurvLearnerSurvBART:surv.bart>: Bayesian Additive Regression Trees
* Model: -
* Parameters: ndpost=50, nskip=250, keep ...
```
on training, it throws the following error message:

```
> learner$train(task, row_ids = part$train)

Error in BART::mc.surv.bart(x.train = x.train, times = times, delta = delta,  : 
  parallel::mcparallel/mccollect do not exist on windows

```
Is there a learner for Windows or is it supposed to switch between `mc.surv.bart` and `surv.bart` automatically?
2) `task_lung$data()` is already shorter than the BART package "lung" data, and has no missing values before imputation is applied.

### Reproducible example

```
> learner$train(task, row_ids = part$train)

Error in BART::mc.surv.bart(x.train = x.train, times = times, delta = delta,  : 
  parallel::mcparallel/mccollect do not exist on windows

```

**Comment by bblodfon** [comment]
Hi @drag05,
1) I didn't know that the `BART::mc.surv.bart()` function doesn't work on Windows! I will update the code to switch to simple `surv.bart` for Windows users. The `surv.bart` doesn't mean that it uses `surv.bart` function btw, it's just a naming scheme we have devised.
2) I removed the missing values from all datasets in `mlr3proba` in the newest versions for easier testing

**Comment by drag05** [comment]
Hi @bblodfon A wrapper could solve it. BART package should have had that. Thank you!

**Comment by drag05** [comment]
@bblodfon The code works now for the Gallery BART example - the learner seems to switch automatically according to the OS. The lung data still comes as complete cases, as before.

```
> task_lung$missings()
     time    status       age  meal.cal pat.karno   ph.ecog  ph.karno       sex   wt.loss 
        0         0         0         0         0         0         0         0         0 
```
Thank you!

**Comment by drag05** [comment]
@bblodfon I am closing this issue now as imputation is secondary. Thank you!
