### ISSUE TITLE
[LRNRQ] Add MOB for surv from package partykit

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3extralearners#4]
### Algorithm

MOB

### Package

partykit

### Supported types

* [x] classif
* [x] regr
* [ ] dens
* [x] surv

### I have checked that this is not already implemented in

  * [x] mlr3
  * [x] mlr3learners
  * [x] mlr3extralearners
  * [x] Other core packages (e.g. mlr3proba)

### Comments

This is already implemented for `classif` and `regr`.

**Comment by sebffischer** [comment]
Do you still think this would be useful @RaphaelS1 Otherwise I would close and would reopen if the request comes again

**Comment by RaphaelS1** [comment]
Happy for you to close
