### ISSUE TITLE
Move flexsurv and parametric to {survivalmodels}

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3extralearners#41]

**Comment by RaphaelS1** [comment]
This shouldn't be closed. There is too much glue code in these learners. But I can transfer the issue to {survivalmodels}

**Comment by sebffischer** [comment]
Is there any plan on doing this? :)

**Comment by RaphaelS1** [comment]
Meeting with John today. Will discuss then.

**Comment by RaphaelS1** [comment]
@bblodfon I tried to use the new `predict.flexsurvreg` method and sometimes get the same results as my implementation in this package and sometimes quite different, in the snippet below they're quite close. Would you mind checking out the code below and letting me know your thoughts? Then if we think our method is better we'll port all the code to extralearners, or if we think we should use the method from `flexsurv` (even if it's "worse" it might still be better just to use the native method) then we'll delete all the extra code here (I'd always prefer the method built into the underlying implementation where possible)

``` r
library(mlr3verse)
#> Loading required package: mlr3
library(mlr3extralearners)
set.seed(237498324)
l = lrn("surv.flexible")
t = tsk("rats")
split = partition(t)


# train learner
l$train(t, row_ids = split$train)

## 1) using extralearners method
pred = l$predict(t, row_ids = split$test)


## 2) using flexsurv method
# get survival probabilities
p = predict(l$model, type = "surv", newdata = t$data(split$test))$.pred

# check all times the same
times = p[[1]]$.time
x = all(unlist(lapply(p, function(.x) all.equal(times, .x$.time))))
ut = unique(times)

if (x) {
  # remove survival probabilities at duplicated time points 
  dup = !duplicated(times)
  surv = t(vapply(
    p, function(.x) .x$.pred_survival[dup],
    numeric(length(ut))
  ))
  colnames(surv) = ut

  # create Matdist
  out = distr6::as.Distribution(1 - surv, fun = "cdf", decorators = "ExoticStatistics")
}

## 3) compare
matplot(as.data.frame(round(pred$distr$survival(1:100), 4)), type = "l")
```

![](https://i.imgur.com/nrQZU4Z.png)

``` r
matplot(as.data.frame(round(out$survival(1:100), 4)), type = "l")
```

![](https://i.imgur.com/EVV56oA.png)

<sup>Created on 2023-10-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bblodfon** [comment]
I checked the example and I also think we should use the `predict` of the package. So simplifying the predict code here in `mlr3extralearners` would be the way to go for `lrn("surv.flexible")`.

What about the `surv.parametric`, seems complicated enough as well, lots of `distr6` code in there :)

**Comment by RaphaelS1** [comment]
Thanks @bblodfon   could you you open a PR to update flexsurv then (which should be primarily be deleting most code!) And I'll review parametric today

**Comment by bblodfon** [comment]
Need this first => https://github.com/RaphaelS1/survivalmodels/pull/45

**Comment by bblodfon** [comment]
@jemus42 FYI, only thing that has changed is that `type = "aft"` is now `form = "aft"` + solved spome minor issues when fitting the `survreg` model

**Comment by jemus42** [comment]
Hmm our benchmark has an `renv.lock` witha fixed extralearners version - I'm now wondering wether it's better to update and change that one argument in the setup code so it'll work correctly for the new version vs. keep the old version in the benchmark because that's technically more accurate as that's the version we actually ran the benchmark with.

**Comment by bblodfon** [comment]
when I use `renv` I install in these cases the **specific commit** that I need, as the package version in not enough

**Comment by bblodfon** [comment]
Nah, just leave it
