### ISSUE TITLE
Some testing functions aren't included with package, need to be added to depends/suggests

### ISSUE THREAD

**Issue by salauer** [mlr-org/mlr3extralearners#44]
Hello mlr team,

I'm new to this universe and am trying to develop a new learner (using the handy reference from [the book](https://mlr3book.mlr-org.com/extending-learners.html#extending-learners). After running `mlr3extralearners::create_learner()` I edited the learner file and tried to run the tests. However, a few of the testing functions are not included in the package or its dependencies, including `load_tests`, `expect_learner`, and `run_autotest`. I found that there is an `expect_learner()` function in the [`mlrng` package](https://rdrr.io/github/mlr-org/mlrng/man/expect_learner.html), but I don't know if that's the correct one to use or deprecated.

It would be really useful for me to know that I'm using the right functions from the right places! Any help you can offer would be much appreciated! Thanks in advance!

**Comment by RaphaelS1** [comment]
Hi @salauer ! Thanks for your interest in the package and extending the universe!
Have you run `devtools::load_all()` ? I think that should load all those functions automatically.

**Comment by salauer** [comment]
Hello @RaphaelS1, I had not! I just now saw that I missed that bit in the book chapter. All the tests pass, thanks!

**Comment by RaphaelS1** [comment]
Great!
