### ISSUE TITLE
Help regarding a new learner (neuralnet)

### ISSUE THREAD

**Issue by FBerding** [mlr-org/mlr3extralearners#46]
Dear Mr. Sonabend,

I’m trying to add a new learner to mlr3 based on the package “neuralnet”. The aim of the learner is to provide different learners which predefine the number of layers and make the size parameters of the different layers accessible for hyperparamter tuning with MLR3.

With the help of your introduction in the mlr3book I created a file for two layers that runs locally very good. However the autotest and the parameter tests do not work. If I run devtools::test() I get the following console output:

```
> devtools::test()
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners
Loading mlr3extralearners


Warnmeldung:
.onUnload failed in unloadNamespace() for 'mlr3extralearners', details:
  call: vapply(hooks, function(x) environment(x)$pkgname, NA_character_)
  error: Werte müssen die Länge 1 haben,
Ergebnis von FUN(X[[1]]) hat aber Länge 0 
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
Fehler in unload(package) : 
  Package mlr3extralearners not found in loaded packages or namespaces
```

Do you have some suggestions for me how I can solve this problem?
I’m looking forward to your answer. Thank you.

**Comment by RaphaelS1** [comment]
Hi @FBerding ! Thanks for your interest in contributing.

> I’m trying to add a new learner to mlr3 based on the package “neuralnet”. The aim of the learner is to provide different learners which predefine the number of layers and make the size parameters of the different layers accessible for hyperparamter tuning with MLR3.

I think this sounds like a useful learner but bear in mind we also have `classif.nnet` and `mlr3keras` that might also serve your purpose.

> With the help of your introduction in the mlr3book I created a file for two layers that runs locally very good. 

Good to hear!

>  error: Werte müssen die Länge 1 haben,
Ergebnis von FUN(X[[1]]) hat aber Länge 0 

This is quite a general error and is very hard (maybe impossible) to help solve without any further code.
Does the following code work: `devtools::document()` ? 
My guess is this will not work and that there is a bug in one of your files, perhaps a missing bracket or comma (this is quite a big guess as I can't see the code). Some ways to check this are to individually source each of your new files and see if the error appears then. If that still doesn't work, I'd be happy to take a look when I get some time if you want to link me to your forked repo.

**Comment by FBerding** [comment]
Hi @RaphaelS1 ,
thank you for your very quick feedback.

I was able to fix the problem. I wrote a R script for saving the most important functions and saved the script in the mlr3extralearners folder. This caused devtools::load_all() to call devtools:load_all() resulting in an infinitive loop. Now all works fine.

However, devtools::test prints an error while executing the autotest file in line 2. 
```
install_learners("classif.neuralnet2Layer")
load_tests("classif.neuralnet2Layer")

test_that("autotest", {
  learner = LearnerClassifNeuralnet2layer$new()
  expect_learner(learner)
  result = run_autotest(learner)
  expect_true(result, info = result$error)
})
```
The error print is
```
Error (test_neuralnet_classif_neuralnet2Layer.R:2:1): (code run outside of `test_that()`)
Error: Argument hat Länge 0
Backtrace:
  1. load_tests("classif.neuralnet2Layer") test_neuralnet_classif_neuralnet2Layer.R:2:0
* actuar cannot be loaded (1)
```

If I running the test file alone I get the error
```
> load_tests("classif.neuralnet2Layer")
Fehler in if (class %in% c("surv", "dens")) { : Argument hat Länge 0
```

Do you have an idea how i can solve the problem?

> I think this sounds like a useful learner but bear in mind we also have classif.nnet and mlr3keras that might also serve your purpose.

Yes, I agree with you. The idea behind the new learners is that nnet provides only one layer whereas keras is very complex. The implementation of the new learners should provide a learner between them providing a medium complexity. In the case I can solve all problems would you be interrest in implementing the learner in mlr3?

**Comment by RaphaelS1** [comment]
> I was able to fix the problem. I wrote a R script for saving the most important functions and saved the script in the mlr3extralearners folder. This caused devtools::load_all() to call devtools:load_all() resulting in an infinitive loop. Now all works fine.

Great!

> Do you have an idea how i can solve the problem?

Again I have a suspicion but it's hard for me to say anything without seeing it. Double check the properties in your learner and make sure all are filled out correctly (this should be automated but perhaps something went wrong somewhere). Feel free to link me to your code and I can take a look when I have some time.

> Yes, I agree with you. The idea behind the new learners is that nnet provides only one layer whereas keras is very complex. The implementation of the new learners should provide a learner between them providing a medium complexity.

Yes I think this is a good argument and will be helpful for many users.

> In the case I can solve all problems would you be interrest in implementing the learner in mlr3?

I'd be very interested as long as you agree to maintain the learner going forward? Would you also consider adding `regr.neuralnet`?

However I've just looked at the code snippet above and I am slightly concerned about the implementation you are using. Why have you chosen to implement several learners with different layers, instead of having the number of layers as a hyper-parameter?

**Comment by FBerding** [comment]
Hi @RaphaelS1,
thank you for your quick reply.

 > However I've just looked at the code snippet above and I am slightly concerned about the implementation you are using. Why have you chosen to implement several learners with different layers, instead of having the number of layers as a hyper-parameter?

I agree. Adding a hyperparameter for defining the number of layers would be more structured. However, I prefer creating different learners because in neuralnet the number of layers is defined with a vector. To implement this hyperparameter I must use ParamUty which can’t be used within hyperparameter tuning. Another solution could be in creating a hyperparameter ‘LayerNumber’, but this would require to initialize the learner with an additional parameter or the ParamSet would change during the training. Thus, it seems for me more clear and structured if the number of layers is predefined and the ParamSet is the same all the time. Furthermore, the size of the different layers can be analyzed with hyperparamter tuning. Sure, this is not the best solution, but I think it is easier.

Up to now I created five learners for 1 to 5 layers. They pass all test successfully. I also followed the steps you described at the end of chapter 6.1.

If this way of implementing the package neuralnet in mlr3 is okay for your team I can do a push request.
If the files for classif are okay I can write the files for regression, too.

**Comment by RaphaelS1** [comment]
Hi @FBerding, I'm sorry but I cannot include the learner as it is currently coded in mlr3extralearners. Whilst I agree that tuning with `ParamUty` is slightly more complex than other tuning, it is not impossible, here is an example from one of my own experiments tuning a neural network:

```R
  ps = ParamSet$new(list(
    ParamFct$new("nodes", levels = c("32", "64", "128", "256")),
    ParamInt$new("k", lower = 1, upper = 4)
  ))
  ps$trafo = function(x, param_set) {
    x$num_nodes = rep(as.integer(as.character(x$nodes)), x$k)
    x$nodes = x$k = NULL
    return(x)
  }
```

In this example the number of nodes in each layer is the same but this could be extended to different numbers.

If you would like to change your learner to be in line with the usual mlr3 practices then I'd be happy to add it to this repo but unfortunately cannot do so as it currently is.

**Comment by FBerding** [comment]
Hi @RaphaelS1 
thank you for your feedback. Your example helped me a lot. I have rewritten the learner. The learner is now constructed as follows:

- There is only one learner for integrating neuralnet in mlr3.
- For the number of layers a hyperparameter ‘layernumber’(ParamInt) is introduced. The user can choose between 1 to 25 layers. I think this could be enough for the most applications. I assume that users who want to model more complex neural nets are going to use keras. However, I can increase the maximal number of layers if you wish.
- For every layer a hyperparameter is introduced (ParamInt) defining the size of the corresponding layer.
- Dependencies between the layernumber and the size parameters are included so that everything will be computed correctly.
- All size parameters can be passed to mlr3tuning.

I run the autotest and the param_test and the learner passed them successfully. I also tested the parameter tuning manually and it works fine.

Do you think this solution would fit into mlr3extralearners?

**Comment by RaphaelS1** [comment]
> Do you think this solution would fit into mlr3extralearners?

Hi @FBerding unfortunately I don't think I was clear enough in what I meant. The example I gave should be used in tuning only. The mlr 'philosophy' is that it isn't the developer's responsibility to alter any of the parameters in a learner (some minor exceptions to this rule) and the hyper-parameters in a `ParamSet` should be those provided by the learner. So in this example we would only expect to see a single `ParamUty` for layers and nodes

**Comment by FBerding** [comment]
Hi RaphaelS1 ,

okay. Now i understand you. Maybe i have the time to create another solution. However, in the moment i have to concentrate on other projects. 

Thank you for your feedback and help!
