### ISSUE TITLE
[LRNRQ] Add <xgb.train()> for counts and ranks from package <xgboost>

### ISSUE THREAD

**Issue by nipnipj** [mlr-org/mlr3extralearners#94]
### Algorithm

`xgboost` for counts and ranks

### Package

`xgboost`

### Supported types

* [x] classif
* [x] regr
* [ ] surv
* [ ] dens

### I have checked that this is not already implemented in

  * [x] mlr3
  * [x] mlr3learners
  * [x] mlr3extralearners
  * [x] Other core packages (e.g. mlr3proba)

### Why do I think this is a useful learner?
Why not?

### Further Optional Comments
I think it would be easily implemented since it will uses `xgb.train()` as in `regr.xgboost` or `classif.xgboost`. 
I think this might be relate to mlr3 ordinal.

**Comment by RaphaelS1** [comment]
Sorry I don't understand the request, what exactly do you want implemented?

**Comment by nipnipj** [comment]
Basically, I would to use `xgboost` algorithm for an ordinal response. 
I tried using `classif.xgboost` and setting the parameter `objetive` to `objective="rank:pairwise"`, but it doesn't work. I do not know whether this will be possible when `mlr3ordinal` is complete, tho.

**Comment by RaphaelS1** [comment]
Sorry I missed your reply! Next time tag me so I see it straight away!
I'm still not sure what you mean by 'doesn't work', can you please provide a reprex

**Comment by nipnipj** [comment]
@RaphaelS1 Currently it is not possible to use an ordinal variable as response with xgboost learner in mlr3. I would like know whether it is possible add this to mlr3.

**Comment by RaphaelS1** [comment]
In which case no this won't be supported until mlr3ordinal is on CRAN. But we can keep this issue open until then

**Comment by sebffischer** [comment]
Closing because of no progress regarding mlr3ordinal
