### ISSUE TITLE
classif.lightgbm leads to crash of R

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlr-org/mlr3extralearners#96]
Hi,

the use of
lrn("classif.lightgbm")

leads to a crash of R. Without error output in the console.
Is this a topic for mlr or rather for lightgbm?

Danke und Grüße!

**Comment by GitHubGeniusOverlord** [comment]
Here is a Reprex. R crashes at the last line of it. "Bomb R Session Aborted" No Error in the Console. 

`library(mlr3verse)
library(data.table)
library(magrittr)
library(mlbench) 


titanic <- Titanic %>% data.table()

#Target and a few predictors to factor
titanic[, Survived := ifelse(Survived == 'No', 0, 1)]
titanic[, Survived := as.factor(Survived)]
titanic[, Sex := ifelse(Sex == 'Male', 1, 0)]
titanic <- titanic[, .(Survived, N, Sex)]

task_penguins <- TaskClassif$new(id='Pizza', backend = titanic, target = 'Survived', positive = '1') 


train_set <- sample(task_penguins$nrow, 0.8 * task_penguins$nrow)
test_set <- setdiff(seq_len(task_penguins$nrow), train_set)

design = benchmark_grid(
  tasks = task_penguins,
  learners = list(lrn("classif.lightgbm")),
  resamplings = rsmp("cv", folds = 3L)
)

bmr = benchmark(design)
`
Last Console Output: "[mlr3] Running benchmark with 3 resampling iterations

**Comment by RaphaelS1** [comment]
No problem for me... Can you please use {reprex} and include session info

``` r
library(mlr3verse)
#> Warning: package 'mlr3verse' was built under R version 4.1.1
#> Loading required package: mlr3
#> Warning: package 'mlr3' was built under R version 4.1.1
library(data.table)
#> Warning: package 'data.table' was built under R version 4.1.1
library(magrittr)
library(mlbench)

titanic <- Titanic %>% data.table()

# Target and a few predictors to factor
titanic[, Survived := ifelse(Survived == "No", 0, 1)]
titanic[, Survived := as.factor(Survived)]
titanic[, Sex := ifelse(Sex == "Male", 1, 0)]
titanic <- titanic[, .(Survived, N, Sex)]

task_penguins <- TaskClassif$new(id = "Pizza", backend = titanic, target = "Survived", positive = "1")

train_set <- sample(task_penguins$nrow, 0.8 * task_penguins$nrow)
test_set <- setdiff(seq_len(task_penguins$nrow), train_set)

design = benchmark_grid(
  tasks = task_penguins,
  learners = list(lrn("classif.lightgbm")),
  resamplings = rsmp("cv", folds = 3L)
)

bmr = benchmark(design)
#> INFO  [10:41:11.652] [mlr3]  Running benchmark with 3 resampling iterations 
#> INFO  [10:41:11.683] [mlr3]  Applying learner 'classif.lightgbm' on task 'Pizza' (iter 2/3) 
#> INFO  [10:41:11.724] [mlr3]  Applying learner 'classif.lightgbm' on task 'Pizza' (iter 3/3) 
#> INFO  [10:41:11.730] [mlr3]  Applying learner 'classif.lightgbm' on task 'Pizza' (iter 1/3) 
#> INFO  [10:41:11.737] [mlr3]  Finished benchmark
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
