### ISSUE TITLE
Learner names deprecated but shown in mlr_learners

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlr-org/mlr3extralearners#97]
Hi,

if I look at the complete mlr_learners list, including extralearners, I get learners
LearnerClassifLiblineaRL1L2SVC
LearnerClassifLiblineaRL1LogReg
LearnerClassifLiblineaRL2L1SVC
LearnerClassifLiblineaRL2L2SVC
LearnerClassifLiblineaRL2LogReg

however later I am informed that these learners are deprecated:
2: In .__LearnerClassifLiblineaRL1L2SVC__initialize(self = self, private = private,  :
  Deprecated. In the future please use `classif.liblinear` with `type = 5`.
3: In .__LearnerClassifLiblineaRL1LogReg__initialize(self = self, private = private,  :
  Deprecated. In the future please use `classif.liblinear` with `type = 6`.
4: In .__LearnerClassifLiblineaRL2L1SVC__initialize(self = self, private = private,  :
  Deprecated. In the future please use `classif.liblinear` with `type = 3`.
5: In .__LearnerClassifLiblineaRL2L2SVC__initialize(self = self, private = private,  :
  Deprecated. In the future please use `classif.liblinear` with `type = 1` or `2`.
6: In .__LearnerClassifLiblineaRL2LogReg__initialize(self = self, private = private,  :
  Deprecated. In the future please use `classif.liblinear` with `type = 0`

Maybe it would be prudent to update the mlr_learners -list. My observation of this problem is however not very deep, as I am new to mlr3, so its rather a question than a request.

Danke und Viele Grüße!

**Comment by mllg** [comment]
@RaphaelS1 Maybe the learners have been deprecated long enough to just remove them now?

**Comment by RaphaelS1** [comment]
They were removed in 7592df7851b6050447a6f06699ca232d95582cbb
